

VIEWMEM = 0

osbyte = $fff4
osword = $fff1
oswrch = $FFEE ;(VDU command)
osasci = $FFE3

;oswrch commands
OSWRCHSETCOLOUR = 19

;osword commands
OSWORDSOUND = 7
OSWORDENVELOPE = 8

;osbytes
OSDEFINETEXTWINDOW = 28

NUMENVELOPES = 4

NUMENTITIES = 10

SCREENADDRESS1HI = 30
SCREENADDRESS1LO = 00

SCREENADDRESS2HI = 58
SCREENADDRESS2LO = 00

SCREENXOFFSET = 32

NUMMETACOLUMNS = 16
NUMMETAROWS = 16

PLAYER_ACCELERATION = 20
PLAYER_FRICTION = 10
PLAYER_FRICTION_SLIDING = 30
PLAYER_SPEED_MAX_RIGHT = 1
PLAYER_SPEED_MAX_LEFT = 255

; SPEED_MAX_UP = 247
; SPEED_MAX_DOWN = 4
SPEED_MAX_UP = 250
SPEED_MAX_DOWN = 5

JUMPSTRENGTHHI = 253
JUMPSTRENGTHLO = 00

JUMPSTRENGTHSLIDINGHI = 254
JUMPSTRENGTHSLIDINGLO = 00

JUMPSTRENGTHLONGYLO = 00
JUMPSTRENGTHLONGYHI = 00
JUMPSTRENGTHLONGXLO = 00
JUMPSTRENGTHLONGXHI = 00

BOUNCESTRENGTHHI = 252
BOUNCESTRENGTHLO = 00


INITIALGRAVITYHI = 0
INITIALGRAVITYLO = 40

RELEASEGRAVITYHI = 0
RELEASEGRAVITYLO = 80

;entity types 
ENTITYTYPENONE = 0
ENTITYPLAYER = 1

;static entity types
STATICENTITYNONE = 0
STATICENTITYRESPAWNER = 2
STATICENTITYLASERV = 3

;gamestates
GAMESTATETITLE = 0
GAMESTATEPLAYING = 1
GAMESTATEPAUSED = 2
GAMESTATEDISPLAYINGTEXT = 3

;player states
PLAYERSTATEINIT = 0
PLAYERSTATEONFLOOR = 1
PLAYERSTATEWALLSLIDING = 2
PLAYERSTATEJUMPING = 3
PLAYERSTATEFALLING = 4
PLAYERSTATEDIVING = 5 
PLAYERSTATESLIDING = 6
PLAYERSTATEONLADDER = 7
PLAYERSTATEBOUNCING = 8
STATEANIMATING = 8
STATEDOOROPEN = 9
STATEDOORCLOSED = 10
STATEMOVE = 11
STATEJUMPPLATFORMINVIS = 12
STATEJUMPPLATFORMVIS = 13
STATEPROXIMITYTRAP = 14

DIVEFORCERIGHTLO = 00
DIVEFORCERIGHTHI = 2
DIVEFORCELEFTLO = 00
DIVEFORCELEFTHI = 254

;animations
PLAYERANIMATIONIDLE = 0
PLAYERANIMATIONWALKRIGHT =1
PLAYERANIMATIONJUMPRIGHT=2
PLAYERANIMATIONLANDRIGHT=3
PLAYERANIMATIONCLIMBLADDER=4
PLAYERANIMATIONJUMPING=5
PLAYERANIMATIONFALLING=6
PLAYERANIMATIONWALLSLIDING = 7
PLAYERANIMATIONDIVING = 8
PLAYERANIMATIONSLIDING = 9
ANIMATIONCRYSTAL = 10
ANIMATIONDOOROPEN=11
ANIMATIONDOORCLOSE=12
ANIMATIONDOORIDLEOPEN=13
ANIMATIONDOORIDLECLOSED=14

WALLJUMPLEFTXLO = 0
WALLJUMPLEFTXHI = 255
WALLJUMPRIGHTXLO = 0
WALLJUMPRIGHTXHI = 1

WALLJUMPYLO = 0
WALLJUMPYHI = 253



;actions
NOACTION = 0
ACTIONMOVELEFT = 1
ACTIONMOVERIGHT = 2
ACTIONJUMP = 3
ACTIONDOUBLEJUMP = 4
ACTIONWALLJUMP = 5
ACTIONINVERTGRAVITY = 6
ACTIONDIVE = 7
ACTIONINTERACT = 8
ACTIONVIEWMEM = 9

ACTIONSETONFLOOR = 0
ACTIONSETJUMPING = 1
ACTIONSETWALLSLIDING = 2
ACTIONSETDIVING = 3
ACTIONSETSLIDING = 4

;keys
KEYW = 1
KEYS = 2
KEYA = 4
KEYD = 8
KEYK = 16
KEYL = 32


BLACK = 0
RED = 1
GREEN = 2
YELLOW = 3
BLUE = 4
MAGENTA = 5
CYAN = 6
WHITE = 7
FLASHINGBLACKWHITE = 8
FLASHINGREDCYAN = 9
FLASHINGGREENMAGENTA = 10
FLASHINGYELLOWBLUE = 11
FLASHINGBLUEYELLOW = 12
FLASHINGMAGENTAGREEN = 13
FLASHINGCYANRED = 14
FLASHINGWHITEBLACK = 15

TILEPAGE1 = $0900
TILEPAGE2 = $0A00
SPRITEPAGE1 = $0c00
SPRITEPAGE2 = $0d00

REVERSEBITSPAGE = $0e00


CONVEYORBELTSPEED = 80


ANICONTROLBYTELOOP = 128
ANICONTROLBYTENEWANIMATION = 129
ANICONTROLDESTROYSELF = 130
ANICONTROLBYTESETSPEED = 131
ANICONTROLBYTEFLIP = 132


DOOROPENDIST = 48


GEOMETRYDATAOFFSET = 2

BITSKIP = 36
BITSKIP2 = 44

WALLSLIDEINITALSPEEDLO = 10
WALLSLIDEINITIALSPEEDHI = 0

WALLSLIDESPEEDLO = 4
WALLSLIDESPEEDHI = 0

SPRITEHEIGHT = 8
SPRITEWIDTH = 8

SOUNDJUMP = 0
SOUNDBOUNCE = 1
SOUNDFLUIDPICKUP = 2

; KEYW=1
; KEYS=2
; KEYA=4
; KEYD=8
; KEYK=16
KEYRETURN=128

ETANKDEFAULTLO=0
ETANKDEFAULTHI=3

COLLISIONNONE = 0
COLLISIONKILL = 1
COLLISIONADDE = 2
COLLISIONTP = 3
COLLISIONADDKEY = 4
COLLISIONBOUNCE =5