

VIEWMEM = 0

osbyte = $fff4
osword = $fff1
oswrch = $FFEE ;(VDU command)
osasci = $FFE3

;oswrch commands
OSWRCHSETCOLOUR = 19

;osword commands
OSWORDSOUND = 7
OSWORDENVELOPE = 8

;osbytes
OSDEFINETEXTWINDOW = 28

NUMENVELOPES = 4

NUMENTITIES = 10

SCREENADDRESS1HI = 30
SCREENADDRESS1LO = 00

SCREENADDRESS2HI = 58
SCREENADDRESS2LO = 00

SCREENXOFFSET = 32

NUMMETACOLUMNS = 16
NUMMETAROWS = 16

PLAYER_ACCELERATION = 20
PLAYER_FRICTION = 10
PLAYER_FRICTION_SLIDING = 15
PLAYER_SPEED_MAX_RIGHT = 1
PLAYER_SPEED_MAX_LEFT = 255

; SPEED_MAX_UP = 247
; SPEED_MAX_DOWN = 4
SPEED_MAX_UP = 253
SPEED_MAX_DOWN = 2



LONGJUMPSTRENGTHXHILEFT = 253
LONGJUMPSTRENGTHXLOLEFT  = 00

LONGJUMPSTRENGTHXHIRIGHT = 3
LONGJUMPSTRENGTHXLORIGHT = 00

LONGJUMPSTRENGTHYHI = 254
LONGJUMPSTRENGTHYLO = 00

JUMPSTRENGTHHI = 253
JUMPSTRENGTHLO = 00

JUMPSTRENGTHSLIDINGHI = 254
JUMPSTRENGTHSLIDINGLO = 00

JUMPSTRENGTHFLIPHI = 252 
JUMPSTRENGTHFLIPLO = 128

JUMPSTRENGTHLONGYLO = 00
JUMPSTRENGTHLONGYHI = 00
JUMPSTRENGTHLONGXLO = 00
JUMPSTRENGTHLONGXHI = 00

BOUNCESTRENGTHHI = 252
BOUNCESTRENGTHLO = 00


INITIALGRAVITYHI = 0
INITIALGRAVITYLO = 40

RELEASEGRAVITYHI = 0
RELEASEGRAVITYLO = 80

LONGJUMPGRAVITYHI = 0
LONGJUMPGRAVITYLO = 30

;entity types 
ENTITYTYPENONE = 0
ENTITYPLAYER = 1
ENTITYCRYSTAL = 2 
ENTITYDOOROPEN = 3 
ENTITYDOORCLOSED = 4
ENTITYPLATFORMINVIS = 5
ENTITYPLATFORMVIS = 6
ENTITYLIFE = 7
ENTITYSPIKETRAP = 8
ENTITYPROJU = 9
ENTITYPROJD = 10
ENTITYPROJL = 11
ENTITYPROJR = 12
ENTITYTELPORTER = 13
ENTITYKEY = 14
ENTITYHBOUNCER = 15
ENTITYVBOUNCER = 16
ENTITYCRAWLER = 17
ENTITYBOUNCER = 18
ENTITYBOUNCERDISABLED = 19
ENTITYTORCHLARGE = 21


;static entity types
STATICENTITYNONE = 0
STATICENTITYRESPAWNER = 2
STATICENTITYLASERV = 3

;gamestates
GAMESTATETITLE = 0
GAMESTATEPLAYING = 1
GAMESTATEPAUSED = 2
GAMESTATEDISPLAYINGTEXT = 3

;player states
PLAYERSTATEINIT = 0
PLAYERSTATEONFLOOR = 1
PLAYERSTATEWALLSLIDING = 2
PLAYERSTATECROUCHING = 3
PLAYERSTATEFALLING = 4
PLAYERSTATEDIVING = 5 
PLAYERSTATESLIDING = 6
PLAYERSTATEONLADDER = 7
PLAYERSTATEBOUNCING = 9

STATEANIMATING = 8
STATEDOOROPEN = 9
STATEDOORCLOSED = 10
STATEMOVE = 11
STATEJUMPPLATFORMINVIS = 12
STATEJUMPPLATFORMVIS = 13
STATEPROXIMITYTRAP = 14
STATEDOORINIT = 27
; PLAYERSTATECROUCHING = 26

DIVEFORCERIGHTLO = 00
DIVEFORCERIGHTHI = 2
DIVEFORCELEFTLO = 00
DIVEFORCELEFTHI = 254

;animations
PLAYERANIMATIONIDLE = 0
PLAYERANIMATIONWALKRIGHT =1
PLAYERANIMATIONJUMPRIGHT=2
PLAYERANIMATIONLANDRIGHT=3
PLAYERANIMATIONCLIMBLADDER=4
PLAYERANIMATIONJUMPING=5
PLAYERANIMATIONFALLING=6
PLAYERANIMATIONWALLSLIDING = 7
PLAYERANIMATIONDIVING = 8
PLAYERANIMATIONSLIDING = 9
ANIMATIONCRYSTAL = 10
ANIMATIONDOOROPEN=11
ANIMATIONDOORCLOSE=12
ANIMATIONDOORIDLEOPEN=13
ANIMATIONDOORIDLECLOSED=14

WALLJUMPLEFTXLO = 0
WALLJUMPLEFTXHI = 255
WALLJUMPRIGHTXLO = 0
WALLJUMPRIGHTXHI = 1

WALLJUMPYLO = 0
WALLJUMPYHI = 253



;actions
NOACTION = 0
ACTIONMOVELEFT = 1
ACTIONMOVERIGHT = 2
ACTIONJUMP = 3
ACTIONDOUBLEJUMP = 4
ACTIONWALLJUMP = 5
ACTIONINVERTGRAVITY = 6
ACTIONDIVE = 7
ACTIONINTERACT = 8
ACTIONVIEWMEM = 9
ACTIONLONGJUMP = 10
ACTIONEXITCROUCH = 11
ACTIONENTERCROUCH = 12

ACTIONSETONFLOOR = 0
ACTIONSETJUMPING = 1
ACTIONSETWALLSLIDING = 2
ACTIONSETDIVING = 3
ACTIONSETSLIDING = 4
ACTIONSETCROUCHING = 5

;keys
KEYW = 1
KEYA = 4
KEYS = 2
KEYD = 8
KEYK = 16
KEYL = 32
KEYP = 64
KEYRETURN = 128


BLACK = 0
RED = 1
BLUE = 2
MAGENTA = 3
GREEN = 4
YELLOW = 5
CYAN = 6
WHITE = 7
FLASHINGBLACKWHITE = 8
FLASHINGREDCYAN = 9
FLASHINGGREENMAGENTA = 10
FLASHINGYELLOWBLUE = 11
FLASHINGBLUEYELLOW = 12
FLASHINGMAGENTAGREEN = 13
FLASHINGCYANRED = 14
FLASHINGWHITEBLACK = 15

TILEPAGE1 = $0900
TILEPAGE2 = $0A00
SPRITEPAGE1 = $0c00
SPRITEPAGE2 = $0d00

REVERSEBITSPAGE = $0e00


CONVEYORBELTSPEED = 255


ANICONTROLBYTELOOP = 128
ANICONTROLBYTENEWANIMATION = 129
ANICONTROLDESTROYSELF = 130
ANICONTROLBYTESETSPEED = 131
ANICONTROLBYTEFLIP = 132


DOOROPENDIST = 48


GEOMETRYDATAOFFSET = 2

BITSKIP = 36
BITSKIP2 = 44

WALLSLIDEINITALSPEEDLO = 10
WALLSLIDEINITIALSPEEDHI = 0

WALLSLIDESPEEDLO = 4
WALLSLIDESPEEDHI = 0

SPRITEHEIGHT = 8
SPRITEWIDTH = 8

SOUNDJUMP = 0
SOUNDBOUNCE = 1
SOUNDFLUIDPICKUP = 2

; KEYW=1
; KEYS=2
; KEYA=4
; KEYD=8
; KEYK=16
; KEYRETURN=128

ETANKDEFAULTLO=0
ETANKDEFAULTHI=3

COLLISIONNONE = 0
COLLISIONKILL = 1
COLLISIONADDE = 2
COLLISIONTP = 3
COLLISIONADDKEY = 4
COLLISIONBOUNCE =5


MMTBRICKWALLL= 0
MMTBRICKWALLR= 1
MMTEMPTYWALL1= 2
MMTEMPTYWALL16=3
MMTSOLIDWALL2=4
MMTSOLIDWALL4=5
MMTSOLIDWALL8=6
MMTSOLIDWALL16=7
MMTSOLIDFLOOR1=8
MMTSOLIDFLOOR2=9
MMTSOLIDFLOOR4=10
MMTSOLIDFLOOR8=11
MMTSOLIDFLOOR16=12
MMTBRICKFLOOR16=13
MMTEARTHFLOOR16=14
MMTEMPTYFLOOR1=15
MMTEMPTYFLOOR2=16
MMTEMPTYFLOOR4=17
MMTEMPTYFLOOR5=18
MMTEMPTYFLOOR8=19
MMTEMPTYFLOOR16=20
MMTCONVEYERLEFT16=23
MMTCONVEYERRIGHT16=24
MMTCONVEYERLEFT8=25
MMTCONVEYERRIGHT8=26
MMTCONVEYERLEFT4=27
MMTCONVEYERRIGHT4=28
MMTCONVEYERLEFT2=29
MMTCONVEYERRIGHT2=30
; MMTEMPTYFLOOR1=21
; MMTEMPTYFLOOR1=22
; MMTEMPTYFLOOR1=23
MMTEMPTYWALL2=33
MMTEMPTYWALL4=34
MMTEMPTYWALL8=35
MMTBRICKCEILING16 = 36

DEFAULTSCREENOPENAIR = 0
DEFAULTSCREENCLOSED = 1
DEFAULTSCREENSHAFTV = 2
DEFAULTSCREENSHAFTH = 3
DEFAULTSCREENFILLED = 4
DEFAULTSCREENCORRIDORH = 5
DEFAULTSCREENCORRIDORV = 6

NUMTILECORRUPTION = 20

; %0000_0001

PALETTEBLACKWHITE = 0 << 4
PALETTEWHITEBLACK = 1 << 4
PALETTEBLACKRED = 2 << 4
PALETTEBLACKYELLOW = 3 << 4
PALETTEBLACKGREEN = 4 << 4
PALETTEBLACKBLUE = 5 << 4
PALETTEBLACKCYAN = 6 << 4
PALETTEBLACKMAGENTA = 7 << 4

FLASHREPEATTIME = 50

DICTIONARY_THE = 0 + 128
DICTIONARY_YOU = 1 + 128
DICTIONARY_IT = 2 + 128
DICTIONARY_GOODSQUARESPRESS = 3 + 128
DICTIONARY_AND = 4 + 128
DICTIONARY_TO = 5 + 128

PLAYERSTARTX = 0
PLAYERSTARTY = 0